#!/usr/bin/env ruby -w

require_relative 'music_manager'
require_relative 'music_input'
require_relative 'music_collection_runner'

music_input = MusicInput.new(MusicManager.new)
MusicCollectionRunner.new(music_input).run
