# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-node-browsers

    working_directory: ~/music-collection

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".ruby-version" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum ".ruby-version" }}

       # Which version of bundler?
      - run:
          name: Install Rspec
          command: gem install rspec

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            rspec --format progress \
                  --format RspecJunitFormatter \
                  --out /tmp/test-results/rspec.xml \
                  --format progress \
                  *_spec.rb

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
